# Generated by Django 4.1.6 on 2023-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cut_url', '0003_alter_shorturl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
